"""update lesson

Revision ID: 04f6190c61fb
Revises: 8040c5b94603
Create Date: 2023-10-26 00:03:24.236747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f6190c61fb'
down_revision = '8040c5b94603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_user', schema=None) as batch_op:
        batch_op.alter_column('mark',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_user', schema=None) as batch_op:
        batch_op.alter_column('mark',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
