"""update lesson

Revision ID: 8040c5b94603
Revises: 2fd648bdba6d
Create Date: 2023-10-26 00:03:12.990854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8040c5b94603'
down_revision = '2fd648bdba6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_user', schema=None) as batch_op:
        batch_op.alter_column('hometask',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_user', schema=None) as batch_op:
        batch_op.alter_column('hometask',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
