"""update lesson

Revision ID: 8ba125c43157
Revises: 04f6190c61fb
Create Date: 2023-10-26 00:03:35.027866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba125c43157'
down_revision = '04f6190c61fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_user', schema=None) as batch_op:
        batch_op.drop_column('begin_at')
        batch_op.drop_column('end_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_at', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('begin_at', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
